
F²óŠ9Ø‘4M@’%s,ïò@"
amenitydrinking_water"
naturalspring
3òÌ²§%¯¹£ÿåóM@4Îğ°šx@"
amenitydrinking_water
3Ì§•å*¦ö"ÚÒM@şú|ïÊY@"
amenitydrinking_water
3Î§•å*­O9&‹ÒM@,Ê[dñY@"
amenitydrinking_water
3Ğ§•å*yeÍ~ÒM@ƒC^Å˜Z@"
amenitydrinking_water
3ú»•å*,F²|ÒM@ğ4™ñ¶Z@"
amenitydrinking_water
3ü»•å*-
»(zÒM@LÓVÛ[@"
amenitydrinking_water
3ş»•å*lûÉÒM@jÉ>#l[@"
amenitydrinking_water
3€¼•å*ZívÒM@x‡o¼–[@"
amenitydrinking_water
3‚¼•å*¢%4îrÒM@ü¹²U[@"
amenitydrinking_water
3„¼•å*z¶ıáÒM@*K¾#tY@"
amenitydrinking_water
3ˆ¼•å*Ê¨2Œ»ÒM@8·S„åY@"
amenitydrinking_water
3Œ¼•å*‡@äãÉÒM@kØï‰uZ@"
amenitydrinking_water
3Ö®¬¼-“HÛøM@-ƒÅ<†ª@"
amenitydrinking_water
ŸøÅ†¨4ÿK­RÕ½M@ÆìNOş@"
amenitydrinking_water"K
imageBhttps://images.mapillary.com/uCHXdVmSIIL4GUSjrhCYfw/thumb-2048.jpg"
	mapillary3027864824117853