
3ñë¹Ô÷Ğô™G@Àe©P8„;@"
amenitydrinking_water
G²ÇŸ÷è%µ¥¤G@+Y\-•;@"
amenitydrinking_water"
name
FÃ¢ntÃ¢nÄƒ
3†¤è­“å$”¾íG@r·ÚyÑ=<@"
amenitydrinking_water
3ˆ¤è­¼îG@fÉw„.@<@"
amenitydrinking_water
3´¤è­wX—	uíG@ç©¹><@"
amenitydrinking_water
3È¤è­La”V2îG@K6hùË><@"
amenitydrinking_water
3Ü¤è­¿¸ùëºíG@wIA\Ş?<@"
amenitydrinking_water
QÎİ¿‹O@º}ÈG@"‘¶ñ';@"
amenitydrinking_water"
sourcevali2544@yahoo.com
3ö®ÆÔI¶ºœ‹G@Bš±h:O;@"
amenitydrinking_water
3âü©ñÍ€ÄÀ‡G@=%Œ¬R;@"
amenitydrinking_water
3¾‡­¨š¬›œë’G@Ky­„î;@"
amenitydrinking_water
P’çª¬[Å,ÅŸ’G@>›+”;@"
amenitydrinking_water"
designationIzvor Galata
G¦ÊÊ÷£9W9Y—G@ÅHåÜÜ~;@"
amenitydrinking_water"
name
fÃ®ntÃ®nÄƒ
3²ïÁÔ¼ÀöİG@;yìÂj•;@"
amenitydrinking_water
3ü¤Â´åaFÂáG@eîµ#ï;@"
amenitydrinking_water
3ş³‹ãç†K3•G@ö›‰éB”;@"
amenitydrinking_water
3–¦€Œ"—3€\‡àG@ºç¯F,ì;@"
amenitydrinking_water
3”™‡†#Áù?eàG@·N©:@"
amenitydrinking_water
Têş™Ç$:‰ø=¢G@ì~_mÖÀ;@"
amenitydrinking_water"
nameizvor"
name:roizvor
3¸Èë¡%«ÏÕVìÃG@{Snƒ;@"
amenitydrinking_water
A–™È¤&qËGRÒšG@4é¥Ö;@"
amenitydrinking_water"
indoorno
A˜™È¤&5vÓwÈšG@¹Ñ¶Pè;@"
amenitydrinking_water"
indoorno
3‚ëÚƒ-.Â^rí–G@#WEƒ‘;@"
amenitydrinking_water
3„ëÚƒ-h}%ë–G@ú?eF‘;@"
amenitydrinking_water
hú‰†è/ñVnXßG@‡'ªmy©:@"
accessyes"
amenitydrinking_water"
coveredno"	
feeno"

lityes
3²£¢ 1ã"R.è—G@ª<Ë=n;@"
amenitydrinking_water
Qäë§ 2aü4îÍ”G@D‰;ƒ+—;@"
amenitydrinking_water"	
feeno"

wheelchairyes
MüÊ­±:-PA4©	H@ø]š&;@"
nameIzvor 2 Branzeni"
amenitydrinking_water
M¢ß­±:í—ôœ™	H@v¸î½&;@"
nameIzvor 1 Branzeni"
amenitydrinking_water
JÀ©Ì©>½øìÊx±G@sôøÑ;@"
amenitydrinking_water"
drinking_wateryes
3ÌªÌ©>›è;®±G@ÿö+S‚Ò;@"
amenitydrinking_water
3šáæ³>”Û›„w±G@‰–PÑ;@"
amenitydrinking_water
3¼áæ³>ùaÎ}ƒ±G@ÎÙLÏÑ;@"
amenitydrinking_water
3†âæ³>æîs|´±G@¡‘¾ÿEĞ;@"
amenitydrinking_water
3º™šŞ>ğÒ—ï*±G@í¿)Ñ;@"
amenitydrinking_water
3ª­ªŞ>Ê¿;;±G@•`€Ğ;@"
amenitydrinking_water
3â­ªŞ>I³Ã© ±G@cÖ‹¡œĞ;@"
amenitydrinking_water
3´Ã­Ş>jU¦ó<±G@2x˜öÍÏ;@"
amenitydrinking_water
3ÆÃ­Ş>\ÃVB±G@Ÿ6ô`œÏ;@"
amenitydrinking_water
3ÌÄ­Ş>&îgg‡±G@X}d)Ğ;@"
amenitydrinking_water
3šÅ­Ş>şÈˆU±G@`4uh¢Ï;@"
amenitydrinking_water
3ÚÅ­Ş>J©•S±G@fŒjl
Ï;@"
amenitydrinking_water
3îÅ­Ş>«´Å5>±G@ç+7¾Î;@"
amenitydrinking_water
3”Æ­Ş>«Éøœ`±G@¦¼±Í;@"
amenitydrinking_water
3¢´Ş>$[§Û#±G@T?Ì¹Ï;@"
amenitydrinking_water
3¬¢´Ş>:`²L±G@u|ÊÖÏ;@"
amenitydrinking_water
3Ô¢´Ş>4lï®±G@€:Ô¥5Ğ;@"
amenitydrinking_water
3–£´Ş>:‚é±G@Ğ(]úÏ;@"
amenitydrinking_water
3úã´Ş>‰Î×Ñİ±G@qU~¾ÒÌ;@"
amenitydrinking_water
3üã´Ş>:îïÇ±G@w*…åtÌ;@"
amenitydrinking_water
3Öä´Ş>«Ù^f3±G@ÄAÍ;@"
amenitydrinking_water
3Øä´Ş>÷MPy*±G@•hÉãiÍ;@"
amenitydrinking_water
3òæ½Ş>Ü‰H±G@£ÎÜCÂÍ;@"
amenitydrinking_water
3öæ½Ş>XÕb±G@bÌLpÍ;@"
amenitydrinking_water
3ç½Ş>yÅO±G@­Ø½ÜÌ;@"
amenitydrinking_water
3¤ç½Ş>%—ÿ~±G@	Ú.~dÌ;@"
amenitydrinking_water
3ºšÃŞ>(¼§>±G@.¿x«Í;@"
amenitydrinking_water
3ª÷ÉŞ>lSát±G@ \®Ù%Ï;@"
amenitydrinking_water
3ö÷ÉŞ>é\ö•±G@Ò¨eÄÎ;@"
amenitydrinking_water
3ˆøÉŞ>-½ì±G@øzRîÎ;@"
amenitydrinking_water
3ŠøÉŞ>
‘Â«›±G@¨õˆ,Ï;@"
amenitydrinking_water
3ôœËŞ>w—Õ…i±G@)HÇ0‚Ï;@"
amenitydrinking_water
3ŒËŞ>¹Šj¶—±G@8ÏÇkÎ;@"
amenitydrinking_water
3 ËŞ>U0Ïï ±G@0ïí–Í;@"
amenitydrinking_water
3´ËŞ>ğ­£Ã±G@¦²ry½Í;@"
amenitydrinking_water
3ÒËŞ>’¨a	µ±G@]‹ mÍ;@"
amenitydrinking_water
3ÎƒÙŞ>*…Š»‹±G@èhú‘ÇÎ;@"
amenitydrinking_water
3€‡ÜŞ>fx¢Ú–±G@|ÜšÍ;@"
amenitydrinking_water
3Ú‡ÜŞ>{æ@jn±G@È»~(Í;@"
amenitydrinking_water
3ö‡ÜŞ>öÿ»OŸ±G@*Å3/Í;@"
amenitydrinking_water
3ŠˆÜŞ>™¿Ÿ±G@.QÃÊÌ;@"
amenitydrinking_water
3ŒˆÜŞ>ïC?®±G@y²›ıÌ;@"
amenitydrinking_water
3ĞˆÜŞ>»¯å±G@aNŠÌ;@"
amenitydrinking_water
3ÊÎåŞ>’¡t3²G@1Ml™gÎ;@"
amenitydrinking_water
3˜ØôŞ>TÆ¿Ï±G@ÙëİÑ;@"
amenitydrinking_water
3ÖÜôŞ>­7Å>\²G@Ì÷çıÚÏ;@"
amenitydrinking_water
3Ê±ß>böp²G@my@4NĞ;@"
amenitydrinking_water
3¬²ß>A´ûúÆ±G@Æ>\Í•Ğ;@"
amenitydrinking_water
3®²ß>9^&/×±G@ı,µĞ;@"
amenitydrinking_water
3¦œ„ß>øU¹Pù±G@É¯2Ñ;@"
amenitydrinking_water
3Ä„ß>Ó¶«¡²G@1ÊØuĞ;@"
amenitydrinking_water
3” „ß>§´¯±G@ÂT3k)Ğ;@"
amenitydrinking_water
3ìŞŒß>è¼kuŞ±G@øßš…Ï;@"
amenitydrinking_water
3‚ßŒß>¸¸M²G@-ÄÏ;@"
amenitydrinking_water
3´µ—ß>ÍjpÎ±G@h)´µÎ;@"
amenitydrinking_water
3Êµ—ß>Îhõã±G@AÕèÕÎ;@"
amenitydrinking_water
3ÂÈ—ß>WÓõD×²G@ˆÒƒ'™Ï;@"
amenitydrinking_water
3¤à—ß>İ0Àô±G@g®ÖeÎ;@"
amenitydrinking_water
3¦à—ß>~@ûìÛ±G@-³ÅVÎ;@"
amenitydrinking_water
3Æà—ß>§b¾º±G@iÜålKÎ;@"
amenitydrinking_water
3Ôà—ß>êÒŞ±G@EÍ¡VâÍ;@"
amenitydrinking_water
3–â—ß>£ñj²G@2Ş ˆÍ;@"
amenitydrinking_water
3šâ—ß>|-è½1²G@w’c¡ŒÍ;@"
amenitydrinking_water
3 â—ß>!zR&5²G@;©Ô‘ÈÍ;@"
amenitydrinking_water
3¶â—ß>İAìL²G@DFœÍ;@"
amenitydrinking_water
3üˆœß>ºßüáB²G@O¯9¬Î;@"
amenitydrinking_water
3î¯Ÿâ>ËX#qE±G@Ò…¢Š,Ï;@"
amenitydrinking_water
3È×Àâ>‘^y5å±G@¨ç8Ó;@"
amenitydrinking_water
3Ú×Àâ>‰–P²G@ö(\ÂÓ;@"
amenitydrinking_water
3¼ı”ã>jB¤ğ°G@qæWs€Ì;@"
amenitydrinking_water
3ÀµÈã>cÿ+á¿´G@FiÊ©øÆ;@"
amenitydrinking_water
3Š©Ôã>ç8·	÷±G@à6éÌ;@"
amenitydrinking_water
3Ì©Ôã>Ò=FÔŸ®G@uyÅøÙ;@"
amenitydrinking_water
CòÛøşAc'¼ßG@jéÀ(÷¥:@"
amenitydrinking_water"
nameYhkhhj
aüè§ÃFŞG$ÀŸ±G@cªO(ú<@"
accessyes"
amenitydrinking_water"	
feeno"
name
FÃ¢ntÃ¢nÄƒ