
,´ÕÏÇ_çğZS	@À®ĞQXó JÀ"
amenitytoilets
,êô€®S/®§^?ÀÙï‰uªıIÀ"
amenitytoilets
;æ¯Æ©q&Å#@À¡Q®¢JÀ"
amenitytoilets"
accessyes
;è¯Æ©"MaJÉ@À;hÀjvJÀ"
accessyes"
amenitytoilets
,ò¡É©Mm=@Àß{nüJÀ"
amenitytoilets
YüŒô$Õ‚r6xÂ?Ào_Q[4JÀ"
amenitytoilets"+
operatorPrefeitura Municipal de Pelotas
RŠ¶Ÿ¢(Åñ2y¹Â?À²Ğ÷0JÀ"
amenitytoilets"	
feeno"
toilets:disposalflush
,²Ù«®)øÀ3FÁ?À¸èd©õ-JÀ"
amenitytoilets
,š‚á“*xXòÂç@À
kcì„JÀ"
amenitytoilets
;à¥İ˜K=»|ëÃ`?À^“_ûIÀ"
accessyes"
amenitytoilets
;â¥İ˜K$¦ŸË/\?ÀÆ"áÖ8ûIÀ"
accessyes"
amenitytoilets