
L„¨¾ç!8¾öÌ’`'@^Ò½ó[@"
amenitytoilets"
toilets:disposal
pitlatrine
>®¼ñœ"İ‘V!¦'@°XÃEn[@"
sourcesurvey"
amenitytoilets
œ¾ÚóÇ"æûó~íæ'@Í£ÑÓ¶[@"
femaleyes"
maleyes"!
toilets:positionseated;urinal"
accessyes"
amenitytoilets"
drinking_wateryes"	
feeno
,¾ï«/`ñ/İ'@œ¶5ØŠ[@"
amenitytoilets
,Êó¾ö/‰£açà'@ÑïVñ¡[@"
amenitytoilets
,ÈÊôëG‹åñ¶÷'@×Ë¥§[@"
amenitytoilets
,ĞÊôëG¨£ˆ±õ'@IGÃ[@"
amenitytoilets
,²ù„îG®—ğ•Š'@¬}ğ˜[@"
amenitytoilets
S´ù„îG&»ã^ª'@*¢p‡—[@"
amenitytoilets"	
feeno"
toilets:handwashingyes