
hâ½ú#É:Á£2š0ÀÈy†¡HÀ"
amenitytoilets"
changing_tableno"	
feeno"
toilets:disposalflush
,¦º½)GÌìó™0ÀNf¼­ô£HÀ"
amenitytoilets
a¨º½)«O(ú2™0ÀÕæ¤œÔ£HÀ"
accessyes"
amenitytoilets"	
feeno"
toilets:disposalflush
,ªº½)‹»‹Aq™0ÀÇªnä£HÀ"
amenitytoilets
,®º½)glÙd™0À?¤„¤HÀ"
amenitytoilets
,°º½)–ªşRP™0À=wÌŠò£HÀ"
amenitytoilets
,²º½)ú‡ã¯™0À<ıûç£HÀ"
amenitytoilets
D´º½)9Lyc™0ÀµÔ02·£HÀ"
amenitytoilets"
descriptionTÃ©rreo
K¶º½)öøsÀd™0ÀœDsS¹£HÀ"
amenitytoilets"
descriptionPrimeiro andar
a¸º½)µ<Lû˜0ÀÌa÷Ã£HÀ"
accessyes"
amenitytoilets"	
feeno"
toilets:disposalflush
aºº½)C¾ğï˜0Àã­âè£HÀ"
toilets:disposalflush"
accessyes"
amenitytoilets"	
feeno
,’éŒ½)ƒ¦€™0À»æŸ*ğ£HÀ"
amenitytoilets
M”éŒ½)O§ŠN™0ÀHå#Ü£HÀ"
amenitytoilets"
changing_tableno"	
feeno
FàË½)°*±!î˜0À’ÿmØ£HÀ"	
feeno"
accessyes"
amenitytoilets
h’›‹Ü)§|cc¹˜0Àª}ßdÀ£HÀ"
access
permissive"
amenitytoilets"	
feeno"
toilets:disposalflush
,Ğ›‹Ü)¦ˆgdë˜0À`#I®£HÀ"
amenitytoilets
,ÆÌÜ)ÙÎœšpš0ÀZóˆvº¡HÀ"
amenitytoilets
,ÊÌÜ)Ÿ5äDš0À	Í	5¡HÀ"
amenitytoilets
Vš‡ğí)ÜqQÒ˜0ÀjÙÿ¥±£HÀ"
accessyes"
amenitytoilets"
toilets:disposalflush
GÊ¡ò)ú@—/™0Àÿ”*Qö£HÀ"
amenitytoilets"
toilets:disposalflush
GÌ¡ò)´‰İˆ8™0ÀïØğ£HÀ"
amenitytoilets"
toilets:disposalflush
GÎ¡ò)?¶3?™0ÀùÿÌ{÷£HÀ"
amenitytoilets"
toilets:disposalflush
,¢Ç¥ò)·T‚™0ÀÌ–QÑı£HÀ"
amenitytoilets
]î¿®ò)şÂá»—0ÀŸ[èJ¤HÀ"
amenitytoilets"
changing_tableno"

feeyes"
unisexyes
lğ¿®ò)a¹ïb«—0À¥@°ôë£HÀ"
accessyes"
amenitytoilets"
changing_tableno"
toilets:disposalflush
MÀ©Üô)á|êX¥˜0ÀÄº¤HÀ"
access
permissive"
amenitytoilets"	
feeno
eŒ˜Ìö)z	ğ˜0À=·uÜ•£HÀ"
accessyes"
amenitytoilets"
toilets:disposalflush"
unisexyes
Všö¼Š*Ïr"˜0ÀÆıG¦C¤HÀ"
amenitytoilets"
toilets:disposalflush"
unisexyes
GšÂ¿™*+xÀ+8˜0À¼"&Ø¤HÀ"
toilets:disposalflush"
amenitytoilets
,Ê¸Ï¸*ÎŸ€7î˜0ÀİƒkI¢£HÀ"
amenitytoilets
,ŠÀĞí*¨;O<g¹0À—zq=e HÀ"
amenitytoilets
,ì¡¢¹0R	Oè±0À¬×ãtHHÀ"
amenitytoilets
,üæ½¹0¾y»oÆ°0ÀHÒ$gHÀ"
amenitytoilets
U’Âš¯2ˆ‘?½˜0À3Ùä£HÀ"
amenitytoilets"
changing_tableno"

wheelchairyes
G²ˆ¤;„	H ¾0ÀÚ˜2Ëù£HÀ"
amenitytoilets"
toilets:disposalflush
GÊ€Ş±;°˜l—‘k0À+g”ÓCœHÀ"
amenitytoilets"
toilets:disposalflush
,®÷¿ÅI¤XÉ"¨µ0ÀdÑÏ/¡HÀ"
amenitytoilets
,¦›ÀÅI·Š´C²®0ÀÍ5^“¡HÀ"
amenitytoilets
,êƒ‰L¢ÀD¼0ÀÒ©+Ÿå¨HÀ"
amenitytoilets