
]ÃÀÖû*Ÿ˚û¢èN@|S¢6ﬂ=@"
amenitydrinking_water"
man_made
water_well"
sourcesurvey
fí“§ì$±∏IVèﬂN@µ†|¨>@"
amenitydrinking_water"
name–ö–æ–ª–æ–Ω–∫–∞"
name:ru–ö–æ–ª–æ–Ω–∫–∞
3ê“©´$˜√^Õ±N@
∑!k≤Ò>@"
amenitydrinking_water
Vú¬£Ü1=qÔ–f˜N@s¥Ù≤7ñ>@"
amenitydrinking_water"
name:enWell"
name:fiKaivo
pí¥§‚A∫À4PœËN@ÖÏa‘ZÔ>@"
name:enWell"
amenitydrinking_water"
name–ö–æ–ª–æ–¥–µ—Ü"
name:deBrunnen