
3Â¼ë±,˜ê5^F@£â¤ÕµüTÀ"
amenitydrinking_water
zä¶ıõ$!„6ïî*F@U=OòÙ8UÀ"
amenitydrinking_water"
drinking_wateryes"
drinking_water:legalyes"
naturalspring
3ˆé¢Ô,Í÷B·McF@Ñõ-óAUÀ"
amenitydrinking_water
3¨ë÷ü1š5g3=UF@³O¶7.*UÀ"
amenitydrinking_water
B¾Òüü13:{ÂTF@ğ¥O)UÀ"
accessyes"
amenitydrinking_water
Bş…ƒ2p%;6TF@ÁçĞXUÀ"
accessyes"
amenitydrinking_water
MâÊ›ƒ2™O±ÅÉUF@eãÁ»UÀ"
accessyes"
amenitydrinking_water"	
feeno
3€‰‰ã2cmTF@ë‚°	Ÿ-UÀ"
amenitydrinking_water
J¼ŒÖëIğqÃ|F@d,‰¢ö<UÀ"
amenitydrinking_water"
drinking_wateryes