
3®¢Ğù'~ÖF†–0@œ8¹ß¡°À"
amenitydrinking_water
3ì£Ğùs˜y¼Ú³0@‚ @†µÀ"
amenitydrinking_water
3ğÒÓùå‘‰¥’ß0@ÅìÀ”ÜÀ"
amenitydrinking_water
3ê×ÓùøşíÕå0@»Å²O¶ÿÀ"
amenitydrinking_water
KœŠÔùBÜ‹®‡0@çˆ!ŞßuÀ"
amenitydrinking_water"
man_made
water_well
[Ì»Ôù¡zµíÅc0@•/ÃÚs´À"
amenitydrinking_water"
man_made
water_well"
sourceBing
3Ğ»Ôù0°Øp¢ƒ0@%€ö~şæÀ"
amenitydrinking_water
3Ò»ÔùÓİu6ä1@Fj8¾À"
amenitydrinking_water
[¨©ß‡ç[zª0@2¡NÀ"
amenitydrinking_water"
man_made
water_well"
sourceBing
[Î¤üq±ı¿Eô0@ÌjÛ¸À"
amenitydrinking_water"
man_made
water_well"
sourceBing
KÔ¢“ÂÅÒIİ‰0@„Ø™BçuÀ"
man_made
water_well"
amenitydrinking_water
[‚¦¥Š°"£’Ô0@f©P8/À"
amenitydrinking_water"
man_made
water_well"
sourceBing
[–§¥ŠÎR²œ„è0@aˆA,ÎÀ"
amenitydrinking_water"
man_made
water_well"
sourceBing
[¨¥Š8<Xµê0@R>Nâ½ÌÀ"
man_made
water_well"
sourceBing"
amenitydrinking_water
[â¿ß…$½a‘²Ù0@¼Y(>ãçÀ"
amenitydrinking_water"
man_made
water_well"
sourceBing
[ä¿ß…$á½ş÷ó0@?€ûğâÃÀ"
amenitydrinking_water"
man_made
water_well"
sourceBing